### ISSUE TITLE
MIOpen Build Issues on CS9 due to Boost 1.72 not compatible with glibc 2.34

### ISSUE THREAD

**Issue by junliume** [ROCmSoftwarePlatform/MIOpen#1540]
So this is a well known issue (I just found out with CS9 steam) with boost1{​69,70,72}​ and glibc-2.34:
[can't build on solaris 11.3 using gcc 8.3.0 · Issue #283 · boostorg/thread (github.com)](https://github.com/boostorg/thread/issues/283)
```
./boost/thread/pthread/thread_data.hpp:60:5: error: missing binary operator before token "_sysconf"
 #if PTHREAD_STACK_MIN > 0
```
and PTHREAD_STACK_MIN is most likely defined as _sysconf such as 
```
#define PTHREAD_STACK_MIN ((size_t)_sysconf(_SC_THREAD_STACK_MIN))
```
**[Approaches Forward]:**

- This PR ([Fix Headers for Boost v1.78+ by JP-Ellis · Pull Request #1490 · ROCmSoftwarePlatform/MIOpen (github.com)](https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1490)) tried to loose the limit of boost version (currently we have to use 1.72).
- However, change in `requirements.txt` alone is not sufficient. @pfultz2 it seems that we have to also change [ROCmSoftwarePlatform/rocm-recipes: Recipes for rocm (github.com)](https://github.com/ROCmSoftwarePlatform/rocm-recipes)? I tried to change the requirements.txt in MIOpen alone, but it results in the following error:
```
Downloading https://github.com/boost/boost/archive/1.79.tar.gz
Download failed with error 404
```
- @pfultz2 Which again is kind of interesting why it is looking for boost on GitHub? It's not available there, right?
