### ISSUE TITLE
CMake Error with target_link_libraries

### ISSUE THREAD

**Issue by darjankrijan** [ROCmSoftwarePlatform/MIOpen#131]
I'm trying to build this for Arch Linux as it seems to be a dependency for tensorflow (ROCm).
I run into a CMake Error that I don't understand with MIOpen-roc-3.0.0:

```
export CXX=/opt/rocm/hcc/bin/hcc
local _cmake_args=(
	-DCMAKE_BUILD_TYPE=Release
	-DCMAKE_INSTALL_PREFIX="${pkgdir}/opt/rocm/miopen"
	-DMIOPEN_BACKEND=HIP
	-DCMAKE_PREFIX_PATH="/opt/rocm/hcc;/opt/rocm/hip"
	-G Ninja
	"${srcdir}/MIOpen-roc-${pkgver}"
)
cmake ${_cmake_args[@]}
-- The C compiler identification is GNU 9.2.0
-- The CXX compiler identification is Clang 10.0.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/rocm/hcc/bin/hcc
-- Check for working CXX compiler: /opt/rocm/hcc/bin/hcc -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.6.3") 
-- Checking for module 'sqlite3'
--   Found sqlite3, version 3.31.1
-- Performing Test HAS_HIP
-- Performing Test HAS_HIP - Success
-- Hip compiler flags:    -isystem /opt/rocm/hip/include -isystem /opt/rocm/hsa/include  -hc -hc -L $<TARGET_FILE_DIR:hcc::mcwamp> -Wl,-rpath $<TARGET_FILE_DIR:hcc::mcwamp> -Wl,--whole-archive  -hc -fPIC -std=c++14 -isystem /opt/rocm/hcc/include  -isystem /opt/rocm/include -ldl  -hc -fPIC -std=c++14 -isystem /opt/rocm/hcc/include  -isystem /opt/rocm/include -Wl,--no-whole-archive -ldl -lm  -hc -fPIC -std=c++14 -isystem /opt/rocm/hcc/include  -isystem /opt/rocm/include
-- hip compiler: /opt/rocm/bin/clang-ocl
-- Performing Test GFX_906_FLAG_VALID
-- Performing Test GFX_906_FLAG_VALID - Failed
-- Performing Test -Werror,
-- Performing Test -Werror, - Failed
-- Build with rocblas
-- Build without scgemm
-- HIP backend selected.
-- extractkernel found: /opt/rocm/hcc/bin/extractkernel
-- AMDGCN assembler: MIOPEN_AMDGCN_ASSEMBLER-NOTFOUND
-- Build without miopengemm
-- Found Boost: /usr/lib64/cmake/Boost-1.72.0/BoostConfig.cmake (found version "1.72.0") found components: filesystem system 
-- Clang tidy found: 10.0.0svn
-- Clang tidy checks: *,-android-cloexec-fopen,-cert-msc30-c,-bugprone-exception-escape,-cert-env33-c,-cert-msc32-c,-cert-msc50-cpp,-cert-msc51-cpp,-clang-analyzer-alpha.core.CastToStruct,-clang-analyzer-optin.performance.Padding,-clang-diagnostic-deprecated-declarations,-clang-diagnostic-extern-c-compat,-clang-diagnostic-unused-command-line-argument,-cppcoreguidelines-avoid-c-arrays,-cppcoreguidelines-avoid-magic-numbers,-cppcoreguidelines-explicit-virtual-functions,-cppcoreguidelines-macro-usage,-cppcoreguidelines-non-private-member-variables-in-classes,-cppcoreguidelines-pro-bounds-array-to-pointer-decay,-cppcoreguidelines-pro-bounds-constant-array-index,-cppcoreguidelines-pro-bounds-pointer-arithmetic,-cppcoreguidelines-pro-type-member-init,-cppcoreguidelines-pro-type-reinterpret-cast,-cppcoreguidelines-pro-type-union-access,-cppcoreguidelines-pro-type-vararg,-cppcoreguidelines-special-member-functions,-fuchsia-*,-google-explicit-constructor,-google-readability-braces-around-statements,-google-readability-todo,-google-runtime-int,-google-runtime-references,-hicpp-braces-around-statements,-hicpp-explicit-conversions,-hicpp-no-array-decay,-hicpp-avoid-c-arrays,-hicpp-signed-bitwise,-hicpp-special-member-functions,-hicpp-uppercase-literal-suffix,-hicpp-use-auto,-hicpp-use-equals-default,-hicpp-use-override,-llvm-header-guard,-llvm-include-order,-misc-misplaced-const,-misc-non-private-member-variables-in-classes,-modernize-avoid-c-arrays,-modernize-pass-by-value,-modernize-use-auto,-modernize-use-default-member-init,-modernize-use-equals-default,-modernize-use-trailing-return-type,-modernize-use-transparent-functors,-performance-unnecessary-value-param,-readability-braces-around-statements,-readability-else-after-return,-readability-isolate-declaration,-readability-magic-numbers,-readability-named-parameter,-readability-uppercase-literal-suffix,-readability-convert-member-functions-to-static,-modernize-use-override,-readability-non-const-parameter
-- Found LATEX: /usr/bin/latex   
-- MIOpen_VERSION= 2.2.0.92-62e7a31-dirty
-- CMAKE_BUILD_TYPE= Release
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
CMake Warning (dev) at src/CMakeLists.txt:456 (target_link_libraries):
  Link library type specifier "debug" is followed by specifier "debug"
  instead of a library name.  The first specifier will be ignored.
Call Stack (most recent call first):
  src/CMakeLists.txt:518 (target_internal_library)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at src/CMakeLists.txt:456 (target_link_libraries):
  The "debug" argument must be followed by a library.
Call Stack (most recent call first):
  src/CMakeLists.txt:518 (target_internal_library)


-- Configuring incomplete, errors occurred!
See also "/home/daren/.cache/pikaur/build/miopen/src/build/CMakeFiles/CMakeOutput.log".
See also "/home/daren/.cache/pikaur/build/miopen/src/build/CMakeFiles/CMakeError.log".
```

I got the following ROCm related AUR packages installed in /opt/rocm:
```
$ pacman -Q | grep "rocm\|miopen\|hcc\|hip"
hcc 3.0.0-1
hip 3.0.0-1
miopengemm 1.1.5.5c980d5-4
rocm-cmake 3.0.0-1
rocm-comgr 3.0.0-2
rocm-device-libs 3.0.0-3
rocm-opencl-runtime 3.0.0-3
rocm-smi 3.0.0-1
rocminfo 3.0.0-1
```

What could be the issue here?

**Comment by pfultz2** [comment]
The newer boost provides a `BoostConfig.cmake` which is picked up by cmake, but this only provides the targets and not the variables. MIOpen doesn't use the targets since it requires using a newer version of cmake when using an older version of boost.

The best solution, right now, is to install the version of boost listed in the `min-requirements.txt` since that is also the version we currently test with. If you build boost as static with `-fPIC` then it will be included in the `.so` so this version of boost will only be a build-time only dependency.

We will look into fixing the build scripts so that it can work with the newer version of boost.

**Comment by darjankrijan** [comment]
Found the culprit:
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/roc-3.0.0/src/CMakeLists.txt#L521

Deleting these two debug lines did the trick.

Now it starts to build and fails linking with an unreferenced "rocblas_gemm_ex"... guess that's because of building rocBLAS with Tensile disabled because that python stuff throws exceptions...
But that's a Tensile problem I guess.

**Comment by darjankrijan** [comment]
I prematurely closed this even though this isn't a real solution to the problem.

Could you look into what's off with the CMakeLists.txt?

I checked if it was due to a too recent cmake build and downgraded from 3.16.4 => 3.13.3 which is the oldest release available in the Arch Linux archive, still the same problem...

**Comment by pfultz2** [comment]
> I checked if it was due to a too recent cmake build and downgraded from 3.16.4 => 3.13.3

Its not the cmake version, its the version of boost that is the problem. You can either install an older version of boost(before 1.70) or you can try setting `Boost_NO_BOOST_CMAKE` to `ON` as mentioned [here](https://cmake.org/cmake/help/latest/module/FindBoost.html#boost-cmake).

**Comment by darjankrijan** [comment]
I forgot to mention that in the meantime I actually built the install_deps.cmake thing to /opt/rocm/miopen-deps that contains Boost 1.64.0.
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=miopen-deps

But it still tries to link to the Boost library the system provides even though providing the prefix with the "CMAKE_PREFIX_PATH" like written in the docs:
https://pastebin.com/vWwBmyiV

```
[100%] Linking CXX executable ../bin/MIOpenDriver
cd /home/daren/scripts/abs/miopen/src/build/driver && /usr/bin/cmake -E cmake_link_script CMakeFiles/MIOpenDriver.dir/link.txt --verbose=1
/opt/rocm/hcc/bin/hcc  -march=znver2 -mtune=znver2 -O3 -pipe -fno-plt -O3 -DNDEBUG -s  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now CMakeFiles/MIOpenDriver.dir/main.cpp.o CMakeFiles/MIOpenDriver.dir/InputFlags.cpp.o  -o ../bin/MIOpenDriver  -Wl,-rpath,/home/daren/scripts/abs/miopen/src/build/lib:/opt/rocm/hip/lib:/opt/rocm/lib:/opt/rocm/rocblas/rocblas/lib: -lstdc++ -amdgpu-target=gfx803 -amdgpu-target=gfx900 -Wno-unused-command-line-argument ../lib/libMIOpen.so.1 -lpthread -lstdc++ -amdgpu-target=gfx803 -amdgpu-target=gfx900 -Wno-unused-command-line-argument /opt/rocm/hip/lib/libhip_hcc.so -hc -L /opt/rocm/hcc/lib -Wl,-rpath /opt/rocm/hcc/lib -Wl,--whole-archive /opt/rocm/hcc/lib/libmcwamp.so.3.0 -Wl,--no-whole-archive -ldl -lm /opt/rocm/hcc/lib/libhc_am.so.3.0 /opt/rocm/lib/libhsa-runtime64.so /opt/rocm/rocblas/rocblas/lib/librocblas.so.0.1 /usr/lib64/libboost_filesystem.a /usr/lib64/libboost_system.a -L/opt/rocmmiopen-deps/lib -lsqlite3 -ldl -lpthread /usr/lib/librt.so -Wl,-rpath-link,/opt/rocm/lib 
ld: /tmp/tmp.EMVr8NI5p2/main.cpp.df8795a242fadd7b2c3f74b92a1f2f2f.host.o: in function `_GLOBAL__sub_I_main.cpp':
main.cpp:(.text.startup+0x7b): undefined reference to `boost::system::generic_category()'
ld: main.cpp:(.text.startup+0x93): undefined reference to `boost::system::system_category()'
ld: ../lib/libMIOpen.so.1: undefined reference to `rocblas_gemm_ex'
ld: ../lib/libMIOpen.so.1: undefined reference to `rocblas_gemm_strided_batched_ex'
ld: ../lib/libMIOpen.so.1: undefined reference to `boost::filesystem::detail::directory_iterator_construct(boost::filesystem::directory_iterator&, boost::filesystem::path const&, boost::system::error_code*)'
```

^ Tries to link with 
```
/usr/lib64/libboost_filesystem.a /usr/lib64/libboost_system.a
```
and not with the ones contained in /opt/rocm/miopen-deps/lib/

The link command line above also contains a broken library path to be fair:
```
-L/opt/rocmmiopen-deps/lib
```

Could any of this be due to the hack deleting the two debug lines?

**Comment by darjankrijan** [comment]
It did work with both installing the Boost 1.64 etc. from `install_deps.cmake` to `/opt/rocm/miopen-deps `**and** providing
```
-DCMAKE_PREFIX_PATH="/opt/rocm/hcc;/opt/rocm/hip;/opt/rocm/miopen-deps"
-DBoost_NO_BOOST_CMAKE=ON
```
in the cmake command.

Now it seems to only break because of the misconfigured rocBLAS.

**Comment by daniellowell** [comment]
Do you require further assistance on this issue thread?

**Comment by darjankrijan** [comment]
The link error is related to rocBLAS, it doesn't build with Tensile for me and some others which is needed to provide the missing "rocblas_gemm_" symbols:
https://github.com/ROCmSoftwarePlatform/rocBLAS/issues/991

Guess nothing can be done about it in this Repo so I'll close this.
