### PR TITLE
Fix compilation on SELS/RHEL after #2657 merged

### LINKED ISSUE #2687: [SLES 15.x][RHEL 8.x] Build failure 'filesystem' file not found after #2657
**[Observation]** 
SLES Error:
```
[2024-01-19T11:45:06.793Z] /long_pathname_so_that_rpms_can_package_the_debug_info/data/driver/MLOpen/addkernels/source_file_desc.hpp:29:10: fatal error: 'filesystem' file not found
[2024-01-19T11:45:06.793Z]    29 | #include <filesystem>
[2024-01-19T11:45:06.793Z]       |          ^~~~~~~~~~~~
```
RHEL Error:
```
[2024-01-19T11:50:12.560Z] [  8%] Linking CXX executable ../bin/addkernels
[2024-01-19T11:50:12.560Z] cd /long_pathname_so_that_rpms_can_package_the_debug_info/data/driver/MLOpen/build_hip/addkernels && /usr/local/lib64/python3.6/site-packages/cmake/data/bin/cmake -E cmake_link_script CMakeFiles/addkernels.dir/link.txt --verbose=1
[2024-01-19T11:50:12.560Z] /opt/rocm-6.1.0-425/llvm/bin/clang++ -O3 -DNDEBUG -s -Wl,--enable-new-dtags,--rpath,$ORIGIN/../lib CMakeFiles/addkernels.dir/include_inliner.cpp.o CMakeFiles/addkernels.dir/addkernels.cpp.o -o ../bin/addkernels 
[2024-01-19T11:50:12.560Z] ld.lld: error: undefined symbol: std::filesystem::weakly_canonical(std::filesystem::__cxx11::path const&)
[2024-01-19T11:50:12.560Z] >>> referenced by include_inliner.cpp
[2024-01-19T11:50:12.560Z] >>>               CMakeFiles/addkernels.dir/include_inliner.cpp.o:(IncludeInliner::ProcessCore(std::istream&, std::ostream&, std::filesystem::__cxx11::path const&, std::filesystem::__cxx11::path const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, bool, bool))
[2024-01-19T11:50:12.560Z] 
[2024-01-19T11:50:12.560Z] ld.lld: error: undefined symbol: std::filesystem::status(std::filesystem::__cxx11::path const&)
[2024-01-19T11:50:12.560Z] >>> referenced by include_inliner.cpp
[2024-01-19T11:50:12.560Z] >>>               CMakeFiles/addkernels.dir/include_inliner.cpp.o:(IncludeInliner::ProcessCore(std::istream&, std::ostream&, std::filesystem::__cxx11::path const&, std::filesystem::__cxx11::path const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, bool, bool))
```

The issue is likely introduced by #2657 

**[Proposal]**:
Within #2657:
```
At the same time, MIOpen is using C++17 standard, and std::filesystem has most of the functionality Boost offers.
Later, we will submit PRs for other components in MIOpen, changing std::string and boost::filesystem::path to std::filesystem::path. Currently, the Linux-specific path operations block Windows MIOpen from executing specific scenarios.
```
Likely we would need the other way around, replace `std::filesystem` with `boost`?

### PR DESCRIPTION
**Pull request by apwojcik**
The PR fixes compilation on SLES and RHEL, which have `std::filesystem` experimental implementation. It also changes the existing `boost::filesystem` to `std::filesystem` - the MSVC standard library is incompatible with Boost and requires extra conversion/translation between Boost and Std. The example is when `boost::filesystem::path` is used with `std::ofstream` - GNU has additional construction accepting Boost path, MSVC does not, and we need to convert each time to either Std path or `std::string`.
The PR is a prerequisite to the upcoming PRs changing path handling from `std::string` to `fs::path` for most use cases.

**Update:** fix https://github.com/ROCm/MIOpen/pull/2687

### CODE REVIEW

**Comment by junliume** [comment]
@apwojcik Thanks for the PR! As a submodule you might need to update FIN (https://github.com/ROCmSoftwarePlatform/MIFin)
http://micimaster.amd.com/blue/organizations/jenkins/MLLIBS%2FMIOpen/detail/detect_filesystem_support/13/pipeline/91

**Comment by apwojcik** [comment]
I have submitted the PR for MIFin. How should I synchronize it to pass CI for MIOpen?

**Review by CAHEK7 — APPROVED** [review]

**Comment by junliume** [comment]
> I have submitted the PR for MIFin. How should I synchronize it to pass CI for MIOpen?

@apwojcik we can update FIN submodule in MIOpen to point to the right commit hash.

*UPDATE*: done below

**Comment by junliume** [comment]
@atamazov @DrizztDoUrden @JehandadKhan need your input here: can these lines below be removed? You are the authors of these lines a few years ago :)
```
error: declaration 'path' is never referenced
```
https://github.com/ROCm/MIOpen/blob/24e64f3f5ed36a7c61e249b1fc53c210e839bf54/src/include/miopen/db.hpp#L39-L43
and
https://github.com/ROCm/MIOpen/blob/24e64f3f5ed36a7c61e249b1fc53c210e839bf54/src/include/miopen/sqlite_db.hpp#L58-L62

**Comment by atamazov** [comment]
@junliume 🟢 It's Ok to remove the forward declaration of `::boost::filesystem::path`.

**Review by junliume — APPROVED** [review]
