### PR TITLE
[Navi21] Fix generic reduction kernels by removing __llvm_amdgcn_s_barrier (SWDEV-274384)

### PR DESCRIPTION
**Pull request by asroy**
remove __llvm_amdgcn_s_barrier(), which is not used but trigger compilation error because of function naming

https://ontrack-internal.amd.com/browse/SWDEV-274384

### CODE REVIEW

**Comment by atamazov** [comment]
@asroy How urgent is this? Should be delivered to 4.6 latest?

**Review by qianfengz — APPROVED** [review]

**Comment by atamazov** [comment]
@asroy @qianfengz Shall we keep the "volatile" W/A introduced in #998?

/cc @junliume

**Comment by qianfengz** [comment]
Yes,  I think  "volatile" should be kept since  PR.1011 and PR.998 are for solving different issues.   PR.1011 is for addressing a building error occurred with the specific version of compiler (4261-STG2),  this building error does not occur with 7235-STG2 and it also does not occur with original version 3681 where SWDEV-274384 is reported.   In a summary,
1) Issues reported by SWDEV-291479 and  original SWDEV-274384 are the same issue (lost indices)
2) Issue occurred with 4261-STG2 is just a building error,  the reason 4261-STG2 is tested is just because the compiler team want me have a try with it for checking the "lost indices" issue

**Comment by atamazov** [comment]
@qianfengz Thanks for the explanation.
