### PR TITLE
[HOTFIX] Fix typo introduced by #2894 and #2902

### PR DESCRIPTION
**Pull request by lshqqytiger**
Even if #2894 and #2902 had an implicit conflict (`outputDesciptor` and `outputDescriptor`), they were merged without solving.
This solves build error `use of undeclared identifier 'outputDesciptor'`.

### CODE REVIEW

**Review by scerzh — APPROVED** [review]
CI was started for the PR

**Comment by scerzh** [comment]
[URGENT] @junliume Can we merge this PR, as it fixes the current compiling error?

**Review by CAHEK7 — APPROVED** [review]

**Review by amberhassaan — APPROVED** [review]
Good.

**Review by junliume — APPROVED** [review]
