### ISSUE TITLE
miir.h header file missing, blocking build from source

### ISSUE THREAD

**Issue by carlushuang** [ROCmSoftwarePlatform/MIOpen#908]
introduced by https://github.com/ROCmSoftwarePlatform/MIOpen/commit/f3921e7d5ca71d3f57333cc9de2bd5aa37e7fbba, now build from source can't success, due to no [`miir.h`](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/src/conv/invokers/mlir_impl_gemm.cpp#L35) in current source.
```
[ 48%] Building CXX object src/CMakeFiles/MIOpen.dir/solver/conv_MP_bidirectional_winograd.cpp.o
/root/MIOpen/src/conv/invokers/mlir_impl_gemm.cpp:35:10: fatal error: 'Miir.h' file not found
#include <Miir.h>
         ^~~~~~~~
[ 48%] Building CXX object src/CMakeFiles/MIOpen.dir/solver/conv_bin_wino3x3U.cpp.o
1 error generated when compiling for gfx900.
src/CMakeFiles/MIOpen.dir/build.make:11461: recipe for target 'src/CMakeFiles/MIOpen.dir/conv/invokers/mlir_impl_gemm.cpp.o' failed
make[2]: *** [src/CMakeFiles/MIOpen.dir/conv/invokers/mlir_impl_gemm.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

If this commit introduce dependency to mlir, need update document or method where to find this header file. because we might not build the docker file every time.

cc @atamazov @jerryyin

**Comment by jerryyin** [comment]
Synced with @carlushuang offline. It becomes inconvenient that `Miir.h` is required when a developer come to debug a non-MIOpen docker image.

I plan on to push a quick PR that wrap the `Miir.h` include into a macro so non-MLIR build does not depend on a MLIR header.

**Comment by atamazov** [comment]
This would break QA Staging testing.

**Comment by atamazov** [comment]
MIOpen promotion process should wait until the fix is merged in `develop`.

**Comment by atamazov** [comment]
via #909
