### ISSUE TITLE
mlir_build.cpp build error with miirGetWorkspaceSize

### ISSUE THREAD

**Issue by 7910f6ba7ee4** [ROCmSoftwarePlatform/MIOpen#1629]
I'm attempting to install MIOpen rocm 5.2.0 via the AUR on Manjaro and patching errors. I'm getting a build error originating from mlir_build.cpp:
```
/home/whisper/.cache/paru/clone/miopen-hip/src/MIOpen-rocm-5.2.0/src/mlir_build.cpp:107:12: error: use of undeclared identifier 'miirGetWorkspaceSize'; did you mean 'MiirGetWorkspaceSize'?
    return miirGetWorkspaceSize(handle());
           ^~~~~~~~~~~~~~~~~~~~
           MiirGetWorkspaceSize
/home/whisper/.cache/paru/clone/miopen-hip/src/MIOpen-rocm-5.2.0/src/mlir_build.cpp:104:5: note: 'MiirGetWorkspaceSize' declared here
int MiirGetWorkspaceSize(const std::string& params)
    ^
/home/whisper/.cache/paru/clone/miopen-hip/src/MIOpen-rocm-5.2.0/src/mlir_build.cpp:107:33: error: reference to type 'const std::string' (aka 'const basic_string<char>') could not bind to an rvalue of type 'MiirHandle' (aka 'void *')
    return miirGetWorkspaceSize(handle());
                                ^~~~~~~~
/home/whisper/.cache/paru/clone/miopen-hip/src/MIOpen-rocm-5.2.0/src/mlir_build.cpp:104:45: note: passing argument to parameter 'params' here
int MiirGetWorkspaceSize(const std::string& params)
                                            ^
```

Trying the suggestion of capitalizing the M results in:
```
/home/whisper/.cache/paru/clone/miopen-hip/src/MIOpen-rocm-5.2.0/src/mlir_build.cpp:107:12: error: no matching function for call to 'MiirGetWorkspaceSize'
    return MiirGetWorkspaceSize(handle());
           ^~~~~~~~~~~~~~~~~~~~
/home/whisper/.cache/paru/clone/miopen-hip/src/MIOpen-rocm-5.2.0/src/mlir_build.cpp:104:5: note: candidate function not viable: cannot convert argument of incomplete type 'MiirHandle' (aka 'void *') to 'const std::string' (aka 'const basic_string<char>') for 1st argument
int MiirGetWorkspaceSize(const std::string& params)
    ^
```
How would I go about solving this? Is miirGetWorkspaceSize supposed to be previously declared?
Also please notify me if I left out any important diagnostics or this is a simple fix, I am new to this.

**Comment by 7910f6ba7ee4** [comment]
Resolved after updating `rocm-llvm-mlir` to 5.2.0
