### ISSUE TITLE
MIOpenDriver Linking error

### ISSUE THREAD

**Issue by kawailee** [ROCmSoftwarePlatform/MIOpen#2893]
I am working on a project to build the ROCM. I got the below linking error for MIOpenDriver. Wonder if I am doing anything wrong here. Anyone has the same issue?

export CXX=/opt/rocm/llvm/bin/clang++; export CC=/opt/rocm/llvm/bin/clang

cd "${src}/MIOpen"; rm -rf build; mkdir -p build; cd build

cmake ../. -DCMAKE_PREFIX_PATH=/opt/rocm -DCMAKE_INSTALL_PREFIX=/opt/rocm -DCMAKE_MODULE_PATH="/opt/rocm/hip/cmake;/opt/rocm/lib" -DMIOPEN_BACKEND=HIP

make -VERBOSE=1

...
[ 93%] Linking CXX executable ../bin/MIOpenDriver
cd /home/wai/misc/workspace/rocm/MIOpen/build/driver && /usr/bin/cmake -E cmake_link_script CMakeFiles/MIOpenDriver.dir/link.txt --verbose=1
/opt/rocm/llvm/bin/clang++ -O3 -DNDEBUG -s -pthread CMakeFiles/MIOpenDriver.dir/InputFlags.cpp.o CMakeFiles/MIOpenDriver.dir/conv_common.cpp.o CMakeFiles/MIOpenDriver.dir/dm_activ.cpp.o CMakeFiles/MIOpenDriver.dir/dm_argmax.cpp.o CMakeFiles/MIOpenDriver.dir/dm_bnorm.cpp.o CMakeFiles/MIOpenDriver.dir/dm_cat.cpp.o CMakeFiles/MIOpenDriver.dir/dm_conv.cpp.o CMakeFiles/MIOpenDriver.dir/dm_convbfp16.cpp.o CMakeFiles/MIOpenDriver.dir/dm_convbfp8.cpp.o CMakeFiles/MIOpenDriver.dir/dm_convfp16.cpp.o CMakeFiles/MIOpenDriver.dir/dm_convfp8.cpp.o CMakeFiles/MIOpenDriver.dir/dm_convint8.cpp.o CMakeFiles/MIOpenDriver.dir/dm_dropout.cpp.o CMakeFiles/MIOpenDriver.dir/dm_fusion.cpp.o CMakeFiles/MIOpenDriver.dir/dm_gemm.cpp.o CMakeFiles/MIOpenDriver.dir/dm_groupnorm.cpp.o CMakeFiles/MIOpenDriver.dir/dm_layernorm.cpp.o CMakeFiles/MIOpenDriver.dir/dm_lrn.cpp.o CMakeFiles/MIOpenDriver.dir/dm_pool.cpp.o CMakeFiles/MIOpenDriver.dir/dm_reduce.cpp.o CMakeFiles/MIOpenDriver.dir/dm_rnn.cpp.o CMakeFiles/MIOpenDriver.dir/dm_softmax.cpp.o CMakeFiles/MIOpenDriver.dir/dm_sum.cpp.o CMakeFiles/MIOpenDriver.dir/dm_tensorop.cpp.o CMakeFiles/MIOpenDriver.dir/main.cpp.o CMakeFiles/MIOpenDriver.dir/registry_driver_maker.cpp.o CMakeFiles/MIOpenDriver.dir/rocrand_wrapper.cpp.o -o ../bin/MIOpenDriver  -Wl,-rpath,/home/wai/misc/workspace/rocm/MIOpen/build/lib:/opt/rocm/lib: ../lib/libMIOpen.so.1.0 /opt/rocm/lib/librocrand.so.1.1 --hip-link --offload-arch=gfx1100 /opt/rocm/lib/libamd_comgr.so.2.7 /opt/rocm/lib/librocblas.so.4.3 /opt/rocm/lib/libamdhip64.so.6.2.24131-e5ec1dc84 /opt/rocm/llvm/lib/clang/19/lib/linux/libclang_rt.builtins-x86_64.a /opt/rocm/lib/libboost_filesystem.a /opt/rocm/lib/libboost_atomic.a /usr/lib/x86_64-linux-gnu/librt.a 
/usr/bin/ld: ../lib/libMIOpen.so.1.0: undefined reference to `LLVMInitializeX86Target'
/usr/bin/ld: ../lib/libMIOpen.so.1.0: undefined reference to `LLVMInitializeX86AsmParser'
/usr/bin/ld: ../lib/libMIOpen.so.1.0: undefined reference to `LLVMInitializeX86TargetMC'
/usr/bin/ld: ../lib/libMIOpen.so.1.0: undefined reference to `LLVMInitializeX86AsmPrinter'
/usr/bin/ld: ../lib/libMIOpen.so.1.0: undefined reference to `LLVMInitializeX86TargetInfo'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by atamazov** [comment]
@kawailee `-Wl,-rpath-link,/opt/rocm/lib` is missing at the end of the linking options, and I have no idea why. Possibly your rocm installation is broken or some env vars that affect CMake or other tools are set in your environment. Your commands are working fine on my machine with 6.0.

[side note] BTW I do not export CXX and CC, it is enough to set CXX inline:
```bash
CXX=... cmake ...
```
Also it is not necessary to set CMAKE_MODULE_PATH and MIOPEN_BACKEND.

**Comment by kawailee** [comment]
Thank you @atamazov .

"/usr/bin/ld" -pie -s --hash-style=gnu --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o ../bin/MIOpenDriver /lib/x86_64-linux-gnu/Scrt1.o /lib/x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/12/crtbeginS.o -L/usr/lib/gcc/x86_64-linux-gnu/12 -L/usr/lib/gcc/x86_64-linux-gnu/12/../../../../lib64 -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib64 -L/lib -L/usr/lib CMakeFiles/MIOpenDriver.dir/InputFlags.cpp.o CMakeFiles/MIOpenDriver.dir/conv_common.cpp.o CMakeFiles/MIOpenDriver.dir/dm_activ.cpp.o CMakeFiles/MIOpenDriver.dir/dm_argmax.cpp.o CMakeFiles/MIOpenDriver.dir/dm_bnorm.cpp.o CMakeFiles/MIOpenDriver.dir/dm_cat.cpp.o CMakeFiles/MIOpenDriver.dir/dm_conv.cpp.o CMakeFiles/MIOpenDriver.dir/dm_convbfp16.cpp.o CMakeFiles/MIOpenDriver.dir/dm_convbfp8.cpp.o CMakeFiles/MIOpenDriver.dir/dm_convfp16.cpp.o CMakeFiles/MIOpenDriver.dir/dm_convfp8.cpp.o CMakeFiles/MIOpenDriver.dir/dm_convint8.cpp.o CMakeFiles/MIOpenDriver.dir/dm_dropout.cpp.o CMakeFiles/MIOpenDriver.dir/dm_fusion.cpp.o CMakeFiles/MIOpenDriver.dir/dm_gemm.cpp.o CMakeFiles/MIOpenDriver.dir/dm_groupnorm.cpp.o CMakeFiles/MIOpenDriver.dir/dm_layernorm.cpp.o CMakeFiles/MIOpenDriver.dir/dm_lrn.cpp.o CMakeFiles/MIOpenDriver.dir/dm_pool.cpp.o CMakeFiles/MIOpenDriver.dir/dm_reduce.cpp.o CMakeFiles/MIOpenDriver.dir/dm_rnn.cpp.o CMakeFiles/MIOpenDriver.dir/dm_softmax.cpp.o CMakeFiles/MIOpenDriver.dir/dm_sum.cpp.o CMakeFiles/MIOpenDriver.dir/dm_tensorop.cpp.o CMakeFiles/MIOpenDriver.dir/main.cpp.o CMakeFiles/MIOpenDriver.dir/registry_driver_maker.cpp.o CMakeFiles/MIOpenDriver.dir/rocrand_wrapper.cpp.o -rpath /home/wai/misc/workspace/rocm/MIOpen/build/lib:/opt/rocm/lib: ../lib/libMIOpen.so.1.0 /opt/rocm/lib/librocrand.so.1.1 /opt/rocm/lib/libamd_comgr.so.2.7.0 /opt/rocm/lib/librocblas.so.4.3 /opt/rocm/lib/libboost_filesystem.a /opt/rocm/lib/libboost_atomic.a /usr/lib/x86_64-linux-gnu/librt.a /opt/rocm/lib/libamdhip64.so.6.2.24131-e5ec1dc84 /opt/rocm/llvm/lib/clang/17/lib/linux/libclang_rt.builtins-x86_64.a -rpath-link /opt/rocm/lib -L/opt/rocm/lib -lamdhip64 -lstdc++ -lm -lgcc_s -lgcc -lpthread -lc -lgcc_s -lgcc /usr/lib/gcc/x86_64-linux-gnu/12/crtendS.o /lib/x86_64-linux-gnu/crtn.o
/usr/bin/ld: ../lib/libMIOpen.so.1.0: undefined reference to `LLVMInitializeX86Target'
/usr/bin/ld: ../lib/libMIOpen.so.1.0: undefined reference to `LLVMInitializeX86AsmParser'
/usr/bin/ld: ../lib/libMIOpen.so.1.0: undefined reference to `LLVMInitializeX86TargetMC'
/usr/bin/ld: ../lib/libMIOpen.so.1.0: undefined reference to `LLVMInitializeX86AsmPrinter'
/usr/bin/ld: ../lib/libMIOpen.so.1.0: undefined reference to `LLVMInitializeX86TargetInfo'

I don't know why clang++ is using linker /usr/bin/ld ; it works if I manually ran the command by switching the linker to "/opt/rocm/llvm/bin/ld.lld"

I have already rebuilt my llvm using LLVM_USE_LINKER="lld" ; but it still calling /usr/bin/ld instead of lld.

Anyhow, it is definitely my environment issue and thank you for pointing me to the right direction.
