### PR TITLE
Unofficially support gfx1031.

### PR DESCRIPTION
**Pull request by atamazov**
~* CK-specific tests are allowed to fail on gfx103X except gfx1030~

~:question: **_TODO enable gfx1031 in CK._** Unofficial support could be handy for our new users and this should be easy to do. @qianfengz @asroy @junliume what do you think? If we are not going to support it, then it may worth reverting changes in tests.~

### CODE REVIEW

**Comment by kvirikroma** [comment]
Tested it on the gfx1031 and got following results:
```
The following tests FAILED:
          3 - test_bn_3d_spatial_test (Failed)
          6 - test_bn_spatial_nhwc_test (Failed)
          7 - test_bn_spatial_test (Failed)
         37 - test_na_train (Failed)
         41 - test_reduce_test (Failed)
```
The error messages for the first 4 failed tests are almost the same as in the #1528 (row_bcast - error: not a valid operand) and they all related to MIOpenBatchNormFwdTrainSpatial.cl.
The error message for 41st test is next:
```
MIOpen(HIP): Error [Do] 'amd_comgr_do_action(kind, handle, in.GetHandle(), out.GetHandle())' AMD_COMGR_ACTION_COMPILE_SOURCE_TO_BC: ERROR (1)
MIOpen(HIP): Error [BuildHip] comgr status = ERROR (1)
MIOpen(HIP): Warning [BuildHip] In file included from /tmp/comgr-402fd8/input/gridwise_generic_reduction_first_call_warpwise_reduce_partial_dims.cpp:29:
/tmp/comgr-402fd8/include/config.hpp:17:2: error: Need to define (only) one GPU target
#error Need to define (only) one GPU target
 ^
In file included from /tmp/comgr-402fd8/input/gridwise_generic_reduction_first_call_warpwise_reduce_partial_dims.cpp:32:
In file included from /tmp/comgr-402fd8/include/tensor_descriptor_helper.hpp:4:
In file included from /tmp/comgr-402fd8/include/common_header.hpp:31:
/tmp/comgr-402fd8/include/amd_buffer_addressing.hpp:29:48: error: use of undeclared identifier 'CK_BUFFER_RESOURCE_3RD_DWORD'
    wave_buffer_resource.config(Number<3>{}) = CK_BUFFER_RESOURCE_3RD_DWORD;
                                               ^
2 errors generated when compiling for gfx1031.

/home/roman/Projects/good_projects_of_good_people/rocm-build/build/miopen/bin/test_reduce_test --float --D 64 3 280 81 --R 0 --ReduceOp 0 --CompType 1 --N 0 --I 0 --scales 1 0 
FAILED: /home/roman/ROCm/MIOpen/src/hipoc/hipoc_program.cpp:300: Code object build failed. Source: gridwise_generic_reduction_first_call_warpwise_reduce_partial_dims.cpp
verify_reduce_no_indices failed
Input Tensor 64, 3, 280, 81
```

I also tried running the tests for master branch from official MIOpen repo and results are almost the same except 26th test (test_handle_test) which fails in master but passes here.
Hope this feedback will be helpful

**Comment by kvirikroma** [comment]
@atamazov Great, thanks)

**Comment by atamazov** [comment]
@kvirikroma Can you please `export MIOPEN_LOG_LEVEL=6`, run one of the failing BN tests and attach console log (as a text file) to the reply. I do not have a gfx1031 system on hand. Thanks.

**Comment by atamazov** [comment]
@kvirikroma No need, I found the reason.

**Comment by atamazov** [comment]
Now CK is enabled for gfx1031. I am hoping that all test shall pass now.
you shall now pass 25

**Comment by kvirikroma** [comment]
@atamazov yes, as you said, BN tests now passed successfully, thank you!

**Review by kvirikroma — APPROVED** [review]

**Comment by atamazov** [comment]
@kvirikroma 
> Here's also a console log (with MIOPEN_LOG_LEVEL=6) for that reduce test Maybe it will be useful in future.

Thanks. With the most recent version of this PR (commit [74e496d](https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1531/commits/74e496d24687fdcf003d886c4d07cefd3adab47c)) the reduce test should work fine. Is it so?

**Comment by kvirikroma** [comment]
@atamazov Yes, I checked it out and it works now 👍

**Review by junliume — APPROVED** [review]

**Comment by atamazov** [comment]
@kvirikroma @junliume Thanks for supporting this PR ;)

**Comment by kvirikroma** [comment]
@atamazov Thank you too)

**Comment by Looong01** [comment]
Dear author, did you add gfx1031 support to the develop branch of the official repo (https://github.com/ROCmSoftwarePlatform/MIOpen)? I have a 6700xt GPU and installed rocm 5.4.2. Now I want to install MIOpen. Can I install it by building MIOpen from source?

**Comment by atamazov** [comment]
@Looong01 You can do that. 6700XT carries Navi22 (gfx1031) onboard. MIOpen has unofficial support for it in develop at least. ~but I am not sure that ROCm 5.4.2 properly supports 6700XT. Let's move further discussions at #1904.~

**Comment by Looong01** [comment]
> @Looong01 You can do that. 6700XT carries Navi22 (gfx1031) onboard. MIOpen has unofficial support for it in develop at least. ~but I am not sure that ROCm 5.4.2 properly supports 6700XT. Let's move further discussions at #1904.~

Thank you very much!

**Comment by Looong01** [comment]
When I use ···cmake -P install_deps.cmake --prefix <miopen-dependency-path>··· to install the dependencies of MIOpen, it returns error with [composable_kernel]:
```
3 errors generated when compiling for gfx1030.
gmake[2]: *** [library/src/tensor_operation_instance/gpu/softmax/CMakeFiles/device_softmax_instance.dir/build.make:76: library/src/tensor_operation_instance/gpu/softmax/CMakeFiles/device_softmax_instance.dir/device_softmax_f16_f16_instance.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:8132: library/src/tensor_operation_instance/gpu/softmax/CMakeFiles/device_softmax_instance.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
[  4%] Building CXX object library/src/tensor_operation_instance/gpu/batched_gemm/CMakeFiles/device_batched_gemm_instance.dir/device_batched_gemm_xdl_f16_f16_f16_gmk_gnk_gmn_instance.cpp.o
lld: error: undefined symbol: __oclc_ABI_version
```

And
```
>>> referenced 41 more times
clang: error: amdgcn-link command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [library/src/tensor_operation_instance/gpu/batched_gemm_add_relu_gemm_add/CMakeFiles/device_batched_gemm_add_relu_gemm_add_instance.dir/build.make:90: library/src/tensor_operation_instance/gpu/batched_gemm_add_relu_gemm_add/CMakeFiles/device_batched_gemm_add_relu_gemm_add_instance.dir/device_batched_gemm_add_relu_gemm_add_xdl_cshuffle_f16_f16_f16_f16_gmk_gnk_gon_gmo_instance.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1843: library/src/tensor_operation_instance/gpu/batched_gemm_add_relu_gemm_add/CMakeFiles/device_batched_gemm_add_relu_gemm_add_instance.dir/all] Error 2
clang: error: unable to execute command: Executable "clang-offload-bundler" doesn't exist!
clang: error: amdgcn-link command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [library/src/tensor_operation_instance/gpu/contraction_bilinear/CMakeFiles/device_contraction_bilinear_instance.dir/build.make:90: library/src/tensor_operation_instance/gpu/contraction_bilinear/CMakeFiles/device_contraction_bilinear_instance.dir/device_contraction_bilinear_m2_n2_k2_xdl_c_shuffle_f32_f32_f32_f32_knnn_instance.cpp.o] Error 1
clang: error: unable to execute command: Executable "clang-offload-bundler" doesn't exist!
clang: error: amdgcn-link command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [library/src/tensor_operation_instance/gpu/contraction_bilinear/CMakeFiles/device_contraction_bilinear_instance.dir/build.make:104: library/src/tensor_operation_instance/gpu/contraction_bilinear/CMakeFiles/device_contraction_bilinear_instance.dir/device_contraction_bilinear_m2_n2_k2_xdl_c_shuffle_f32_f32_f32_f32_mknn_instance.cpp.o] Error 1
clang: error: unable to execute command: Executable "clang-offload-bundler" doesn't exist!
clang: error: amdgcn-link command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [library/src/tensor_operation_instance/gpu/contraction_bilinear/CMakeFiles/device_contraction_bilinear_instance.dir/build.make:118: library/src/tensor_operation_instance/gpu/contraction_bilinear/CMakeFiles/device_contraction_bilinear_instance.dir/device_contraction_bilinear_m2_n2_k2_xdl_c_shuffle_f32_f32_f32_f32_mnnn_instance.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:2243: library/src/tensor_operation_instance/gpu/contraction_bilinear/CMakeFiles/device_contraction_bilinear_instance.dir/all] Error 2
gmake: *** [Makefile:166: all] Error 2
Command failed: ['/usr/bin/cmake', '--build', '/opt/MIOpen/install_dir/cget/build/tmp-98346ae155cf4ee8a4be00beb90b392d/build', '--config', 'Release', '--', '-j', '8']
Failed to build package composable_kernel
1
CMake Error at install_deps.cmake:7 (message):
  Process failed:
  COMMAND;/opt/MIOpen/install_dir/bin/cget;-p;/opt/MIOpen/install_dir;install;-U;-f;requirements.txt
Call Stack (most recent call first):
  install_deps.cmake:100 (cget_exec)
  install_deps.cmake:117 (cget)
```

**Comment by atamazov** [comment]
@Looong01 This is off-topic here. Please remove your comment and then open ticket in https://github.com/ROCmSoftwarePlatform/composable_kernel.

**Comment by Looong01** [comment]
Thank you. I have solved it and built and installed MIOpen from source.
However, My card is 6700xt, so when I use PyTorch, it always gives warning: ```IOpen(HIP): Warning [SQLiteBase] Missing system database file: gfx1030_20.kdb Performance may degrade. Please follow instructions to install: https://github.com/ROCmSoftwarePlatform/MIOpen#installing-miopen-kernels-package```
Hince, how can I build the kernel database for my own GPU? Like ```gfx1030_20.kdb```.

**Comment by atamazov** [comment]
@Looong01 Ignore this warning. IIRC the precompiled binaries (.kdb) are not supplied for your GPU. But this only affects initial runs of networks on your system, because MIOpen supports per-user binary cache for all GPUs, including yours. More info at https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/doc/src/cache.md

**Comment by atamazov** [comment]
@Looong01 Please ask any future questions related to gfx1031 in #1309. This page is intended to discuss specific pull request only.
